osx_image: xcode11.4
language: objective-c

cache:
  directories:
  - Tests/Mac/Pods
  - Tests/iOS/Pods
  - Tests/Swift/Pods
  - Tests/Swift-iOS/Pods

install:
  - cd Tests/
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install --project-directory=./Mac
  - bundle exec pod install --project-directory=./iOS
  - bundle exec pod install --project-directory=./Swift
  - bundle exec pod install --project-directory=./Swift-iOS

script:
  - set -o pipefail
  - xcodebuild -project ./Framework/KissXMLTests.xcodeproj -scheme "KissXMLTests (macOS)" -sdk macosx -arch x86_64 test | xcpretty -c
  - travis_retry xcodebuild -project ./Framework/KissXMLTests.xcodeproj -scheme "KissXMLTests (iOS)" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.4" test | xcpretty -c
  - xcodebuild -project ../KissXML.xcodeproj -scheme "KissXML (tvOS)" -sdk appletvsimulator -arch x86_64 build | xcpretty -c
  - xcodebuild -project ../KissXML.xcodeproj -scheme "KissXML (watchOS)" -sdk watchos build | xcpretty -c
  - xcodebuild -workspace ./Mac/KissXML.xcworkspace -scheme KissXMLTests -sdk macosx -arch x86_64 test | xcpretty -c
  - travis_retry xcodebuild -workspace ./iOS/KissXML.xcworkspace -scheme KissXMLTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.4" test | xcpretty -c
  - xcodebuild -workspace ./Swift/KissXML.xcworkspace -scheme KissXMLSwiftTests -sdk macosx -arch x86_64 test | xcpretty -c
  - travis_retry xcodebuild -workspace ./Swift-iOS/KissXML.xcworkspace -scheme KissXMLSwiftTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.4" test | xcpretty -c
  - bundle exec pod lib lint ../KissXML.podspec
  - swift test -c release
